### ISSUE TITLE
mfarre/Video-LLaVA-7B-hf-CinePile does not appear to have a file named config.json

### ISSUE THREAD

**Issue by funnylittleman** [mfarre/Video-LLaVA-7B-hf-CinePile#1]
Hello! I've tried to test the model using the provided notebook. But the model loading failed with the following error:

> OSError: mfarre/Video-LLaVA-7B-hf-CinePile does not appear to have a file named config.json. Checkout 'https://huggingface.co/mfarre/Video-LLaVA-7B-hf-CinePile/tree/main' for available files.

**Comment by mfarre** [comment]
Hello @funnylittleman!

I guess that 'from_pretrained()' tried to download the model and it failed but as the folder already exist in your system now, it does not go again to hugging face and download all the files again.

You can read more about this issue here: https://github.com/huggingface/transformers/issues/27954

I hope it helps.

**Comment by funnylittleman** [comment]
Hello and thank you for the quick answer!
I try to run the code in a completely new colab notebook, so there is definitely no such folder already exists. Also, if you open https://huggingface.co/mfarre/Video-LLaVA-7B-hf-CinePile/tree/main , there is really no config.json file.

**Comment by mfarre** [comment]
I just changed the code to load the original model and then apply the peft fine-tune. I hope it works for you now!
